#!/bin/bash


exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/var/log/ibm-cos-plugin-diag.log 2>&1

chmod 755 /var/log/ibm-cos-plugin-diag.log

file="/binary/kubelet-plugins/volume/exec/ibm~ibmc-s3fs/ibmc-s3fs"
hostname="$1"

function check_mount_status {
    mountList=$(mount | grep "type fuse.s3fs" | awk '{for(i=1;i<=NF;i++) if ($i=="on") print $(i+1)}')
    echo $mountList
    while read -r line; do
        echo "Checking $line"
        command=$(timeout -t 30 -s 9 ls -al $line 2>&1)
        if [ $? -ne 0 ]
        then
            echo "$(date +%Y-%m-%d-%H:%M:%S): $hostname: Error: MountPointAccessError: $command"
        else
            echo "$(date +%Y-%m-%d-%H:%M:%S): $hostname: Info: Able to access \"$line\""
        fi
    done <<< "$mountList"

}


echo "****Checking driver binary under Kube plugin path****"
if [ -f "$file" ]
then
        echo "$(date +%Y-%m-%d-%H:%M:%S): $hostname: Info: Found \"$file\""
else
        echo "$(date +%Y-%m-%d-%H:%M:%S): $hostname: Error: DriverBinaryNotFound: Binary \"$file\" not found."
fi

echo "****Checking status of s3fs mount-points****"
mountList=$(mount | grep "type fuse.s3fs" | awk '{for(i=1;i<=NF;i++) if ($i=="on") print $(i+1)}')
chrlen=${#mountList}
if [ $chrlen == 0 ]
then
    echo "$(date +%Y-%m-%d-%H:%M:%S): $hostname: Info: No S3FS mount-point found on the host"
else
    check_mount_status
fi
while true; do sleep 1; done
